version: "2"
run:
  go: "1.24"
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - whyNoLint
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G204
        - G304
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/715d/go-truenas
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
